### PR TITLE
Upgrade for Cake 3.0

### PR DESCRIPTION
**Pull request by ADmad**
Doh, I used `git mv` to move all files to new location yet it shows old ones as deleted :(

- [x] ~~The component needs to be updated to account for the fact that data array won't have model name keys anymore.~~ Component was removed
- [x] Support for `_serialize` = `true` should be added as done for JsonView in Cake 3.1

For now I am not raising my hand to take care of either :)

### CODE REVIEW

**Comment by josegonzalez** [comment]
You need to move the files in 1 commit, then make changes in another.

**Comment by ADmad** [comment]
Lesson learned for future, not going to spend time again on this one.

**Comment by ADmad** [comment]
Got back history https://github.com/FriendsOfCake/cakephp-csvview/blame/2.0/src/View/CsvView.php  though not really useful due to the white space change.

**Comment by ADmad** [comment]
@josegonzalez This is good to go imo. The component isn't essential for using the View class itself, so I suggest just drop it for now. It can be reintroduced later.

**Comment by josegonzalez** [comment]
Remove the component. I was never fond of it anyhow - I don't know why I even merged it in the first place...

**Comment by ADmad** [comment]
Done

**Comment by jhli** [comment]
So the 3.c branch is in a usable state now?

**Comment by ADmad** [comment]
Yes

**Comment by josegonzalez** [comment]
You probably want `master` for 3.x support.

**Pull request merged**
