### PR TITLE
Use view options/config instead of special view vars.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by josegonzalez** [comment]
This breaks BC, right?

**Comment by ADmad** [comment]
Yes it does. Using the special view var  `_serialize` works in 4.0 will throw notice. So people have to update that, so might as well update other CsvView specific options too.

**Comment by josegonzalez** [comment]
Okay so this is specifically for 4.0 or are we bumping major and saying its compatible with 3.x and 4.x?

**Comment by ADmad** [comment]
This is specifically for 4.0 compatibility. It's not feasible to have a version which would be compatible with both Cake 3 and 4.

**Comment by ADmad** [comment]
In case you missed it the PR is targeted to the `cake-4.x` branch I had created earlier for Cake 4 compatibility. We can merge it to master and make a new major release once Cake 4.0 is released.

**Pull request merged**
