### PR TITLE
No deprecation

### PR DESCRIPTION
**Pull request by Modicrumb**
I tried my best to make it deprecation free in CakePHP 3.6. As a result it's probably not BC with CakePHP versions less than 3.5. I've also updated the documentation for the new withDownload method.

### CODE REVIEW

**Comment by dereuromark** [comment]
Can you resolve the conflict?

**Comment by dereuromark** [comment]
Don't forget to also adjust composer then and set proper min version for the framework
3.0 sure aint true anymore.

**Comment by Modicrumb** [comment]
I've resolved the conflict, regardless, tests do not pass because I'm still using the deprecated method type() instead of withType(), because withType() does not properly replace type() for new types. Meaning I am just using type(). Deprecation errors come through due to this though. I wasn't sure if I should just file a separate issue in the cakephp github. But I would need to set up a test to make sure that I'm right about withType not handling new types like type() did.

**Comment by Modicrumb** [comment]
I'm baffled at the Fatal error: Call to undefined method Cake\Http\Response::getType() in /home/travis/build/FriendsOfCake/cakephp-csvview/tests/TestCase/View/CsvViewTest.php on line 41

**Comment by Modicrumb** [comment]
Alright so getType is not included until 3.5.5 my bad, will fix this when I get home

**Comment by dereuromark** [comment]
I helped.
The Requirements section in README should mention 3.5.5+ then, as well.
Otherwise all good and we can release a minor here, since this is all BC then.

**Comment by dereuromark** [comment]
Now we just need to fix CS.

**Pull request merged**
